# Generated by Django 4.1.4 on 2022-12-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtag',
            old_name='obj_id',
            new_name='object_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.TextField(choices=[('N', 'Not Sent'), ('S', 'Sent'), ('R', 'Read')], default='N', verbose_name='Sending status'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtag',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
    ]
