# Generated by Django 4.1.4 on 2022-12-28 10:19

from django.db import migrations, models
import django.db.models.deletion
import mailing.validators.phone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_rename_obj_id_itemtag_object_id_alter_message_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Operator Name')),
                ('code', models.CharField(max_length=255, verbose_name='Operator Code')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientfilter',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='clientfilter',
            name='operator_code',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.clientfilter'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[mailing.validators.phone.validate_phone]),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.TextField(choices=[('N', 'Not Sent'), ('S', 'Sent')], default='N', verbose_name='Sending status'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tag Value'),
        ),
        migrations.AddField(
            model_name='client',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.operator'),
        ),
        migrations.AddField(
            model_name='clientfilter',
            name='operators',
            field=models.ManyToManyField(to='mailing.operator'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('phone_number', 'operator', 'time_zone')},
        ),
        migrations.RemoveField(
            model_name='client',
            name='operator_code',
        ),
    ]
