# Generated by Django 4.1.4 on 2022-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_time_zone_alter_mailing_client_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_time',
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Message created at'),
        ),
    ]
